### ISSUE TITLE
Deploy onchain rln to simulator + new urls

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/waku-simulator#31]
With the latest changes, now we have onchain RLN working with a private network. This issue tracks:
- [x] Deploy the latest version to the sim machine (`deploy-wakusim` branch)
- [x] Add two more endpoints, see below.

So we have:
* https://simulator.waku.org/
* https://explorer.waku.org/
* https://rpc.waku.org/

**Comment by stubbsta** [comment]
Two additional endpoint/services needed to be exposed to allow the waku-simulator `web` service to access the `api` service externally:
 API_URL=http://localhost:8090
 WS_API_URL=ws://localhost:8090
see https://github.com/status-im/infra-misc/commit/3276499a for details

**Comment by stubbsta** [comment]
The remote waku-simulator deployment has an issue where each nwaku node has intermittent connectivity to only one peer.
I didn't see this issue locally because I had not pulled the latest docker image for nwaku in a while, so I was running `v0.25.0-rc.0-64-g3c8237` instead of the latest 'v0.25.0-rc.0-87-g2aa835'.
When running the actual latest locally I saw the same connectivity issue.
I removed all changes for onchain RLN locally to ensure that this was not what was causing the issue (it was not).
I have notified the nwaku team about this issue and they will investigate.

**Comment by stubbsta** [comment]
The waku-simulator deployment on the remote host is still not working.
Locally I have installed the same docker and docker-compose versions as the remote host and it still works locally.
The remote host deploys the simulator without the `--compatibility` mode but this is only applicable if the docker-compose version is v2 and newer.
The next step is to pull from an old commit, prior to the onchain additions, to see if that still works on the remote host. If it does work then I will try running the onchain commits to see which change breaks things.

**Comment by stubbsta** [comment]
https://github.com/status-im/infra-misc/issues/268

**Comment by stubbsta** [comment]
The remote host specific issue of peer connectivity was fixed, see https://github.com/status-im/infra-misc/issues/268 for details.
The firewall rules needed to be updated for the block explorer to work.
