### ISSUE TITLE
Integrate RLN v2 into waku-simulator

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/waku-simulator#44]
Integrate RLN v2 into waku-simulator

**Comment by stubbsta** [comment]
Here is a very basic test plan to verify the RLNv2 functionality:
https://www.notion.so/Waku-RLNv2-End-to-End-Testing-with-Waku-simulator-6f50a5613eb44ae38e2dbbcfa72b7417

**Comment by stubbsta** [comment]
Here is an overview of the objective for the RLNv2 testing and how we alter the nwaku code in order to bypass the API checks:
1) We want to publish a message or messages using the API as entry point (just because this is the most convenient/quick way) and we want to be able to exceed the message limit to verify that the message is then not published and the stats should show this is an Invalid/Spam RLN Message.
-I would want to test this with autosharding and the default Pubsub-topic by simply sending a POST e.g.
```
 curl -X POST "http://127.0.0.1:8645/relay/v1/auto/messages" \
 -H "content-type: application/json" \
 -d '{"payload":"'$(echo -n "Hello Waku Network - from Anonymous User" | base64)'","contentTopic":"/my-app/2/chatroom-1/proto"}'
 ```
Obstacles/side quests:
1) The API does some of message validity checks which fail if the message limit is exceeded.
this is solved by commenting out the validateMessage calls in `handlers.nim`
2) The method which appends the RLN proof to the message does a nonce value check
- the nonce is basically a counter to check how many messages have already been sent in a single epoch
- this is bypassed by commenting out the nonce limit check in `nonce_manager.nim`
3) The method which appends the RLN proof to the message uses the nonce value as the messageId parameter for generating the proof and will fail if the messageId exceeds the message limit or if the messageId is the same within the same epoch.
- we need to modify the nonce/messageId value to not exceed the message limit when we attempt to publish above the limit.
- the `unsafeRLNAppendProof` method (https://github.com/waku-org/nwaku/blob/a46d4451eb20e7724f8ac056871b0dfac5fd99a9/tests/waku_rln_relay/rln/waku_rln_relay_utils.nim#L8-L27) forces the nonce to always be zero for negative testing, but we want the messages below the limit to be successful
- there fore we need the nonce value to increase, but then wrap around back to zero once the message limit is reached

**Comment by alrevuelta** [comment]
Closed by https://github.com/waku-org/waku-simulator/pull/45
